# Build Test Action
# -----------------
# - Builds the app as debug to test if it compiles
#   Runs on ubuntu-latest
#   Runs the command "yarn tauri build --bundle none"
#   Runs on every PR to the main branch

name: Build Test

on:
    pull_request:
        types:
            - opened
            - reopened

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            # Sets up Node
            - name: Setup Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  
            # Installs Rust
            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
            
            # Install Ubuntu deps
            - name: Install ubuntu deps
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                sudo apt-get update
                sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
            
            # Runs "yarn install"
            - name: Install NPM packages
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            # Runs "yarn build:debug"
            - name: Build with --debug flag
              uses: borales/actions-yarn@v4
              with:
                  cmd: build:debug
                  
            - uses: tauri-apps/tauri-action@v0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
